[package]
name = "pst"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
axum = "0.8.4"
hex = "0.4.3"
rand = "0.9.2"
rust-ini = "0.21.1"
tokio = { version = "1.47.1", features = ["full"] }
url = "2.5.4"
